#!/bin/bash

echo "================= Preparing cache ====================="

echo "Installing wheel"
pip install wheel

echo "Preparing wheels"
pip wheel --wheel-dir=/tmp/wheelhouse$(echo $TRAVIS_PYTHON_VERSION) pytest pytest-cov pytest-flakes pytest-pep8 python-dateutil arrow six>1.5 python-coveralls

echo "Preparing commands"
echo "passive" >> cmd
echo "mkdir ./$TRAVIS_PYTHON_VERSION" >> cmd
for wheel in $(find /tmp/wheelhouse$(echo $TRAVIS_PYTHON_VERSION) -type f)
do
    echo "put $wheel ./$TRAVIS_PYTHON_VERSION/$(basename $wheel)" >> cmd
done

echo "Install ftp"
sudo apt-get install ftp

echo "Preparing .netrc"
echo "machine ovh.nikitamarchant.com login travis password $PASSWD" > ~/.netrc
chmod 600 ~/.netrc

echo "Uploading"
ftp ovh.nikitamarchant.com < cmd

echo "================== Cache is done ======================"
