@@grammar::contentline
@@whitespace :: None

start = contentline $ ;
full = {(contentline ?"\r?\n")}+ ;

ALPHADIGIT_MINUS_PLUS = ? "[a-zA-Z0-9\-]+";
DQUOTE = '"' ;
QSAFE_CHAR_STAR    = ?"[^\x00-\x08\x0A-\x1F\x22\x7F]*";
SAFE_CHAR_STAR     = ?"[^\x00-\x08\x0A-\x1F\x22\x2C\x3A\x3B\x7F]*";
VALUE_CHAR_STAR    = ?"[^\x00-\x08\x0A-\x1F\x7F]*";

contentline   = name:name {(";" params+:param )}* ":" value:value ;
name          = ALPHADIGIT_MINUS_PLUS ;

param         = name:param_name "=" values+:param_value {("," values+:param_value)}* ;
param_name    = ALPHADIGIT_MINUS_PLUS ;
param_value   = quoted_string | paramtext ;

paramtext     = SAFE_CHAR_STAR ;
value         = VALUE_CHAR_STAR ;
quoted_string = DQUOTE @:QSAFE_CHAR_STAR DQUOTE ;
