name: Publish package 📦

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:


jobs:
  build-and-publish:
    name: Build package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Build the package
      run: python -m build

    - name: Publish package 📦 to PyPI 🎉 (POC, using dev pypi for now)
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
